create or replace table participant_descriptives as

with

base_participants as (

select
    a.war_id,
    b.war_name,
    a.c_code,
    a.participant,
    a.side,
    a.start_date,
    a.end_date,
    extract(year from a.start_date)::integer start_year,
    extract(year from a.end_date)::integer end_year,
    a.start_date_estimated,
    a.end_date_estimated,
    a.battle_deaths,
    a.battle_deaths_estimated
from participants a
join wars b on a.war_id = b.war_id),

participant_descriptor_summaries as (

select
    'x' timeframe,
    war_id,
    war_name,
    c_code,
    round(avg(terrorism_deaths), 2) terrorism_deaths,
    round(avg(mid_dyads), 2) mid_dyads,
    round(avg(mid_dyads_initiated), 2) mid_dyads_initiated,
    round(avg(mid_dyads_targeted), 2) mid_dyads_targeted,
    round(avg(mid_dyads_joined), 2) mid_dyads_joined,
    round(avg(allied_countries), 2) allied_countries,
    round(avg(trade_countries), 2) trade_countries,
    round(avg(money_flow_in), 2) money_flow_in,
    round(avg(money_flow_out), 2) money_flow_out,
    round(avg(imports), 2) imports,
    round(avg(exports), 2) exports,
    round(avg(military_expenditure), 2) military_expenditure,
    round(avg(military_personnel), 2) military_personnel,
    round(avg(iron_steel_production), 2) iron_steel_production,
    round(avg(energy_consumption), 2) energy_consumption,
    round(avg(population), 2) population,
    round(avg(urban_population), 2) urban_population,
    avg(urban_population_growth_rate) urban_population_growth_rate,
    avg(cinc_score) cinc_score,
    round(greatest(avg(land_mass_exchange_gain), 0), 2) land_mass_exchange_gain,
    round(greatest(avg(population_exchange_gain), 0), 2) population_exchange_gain,
    round(greatest(avg(land_mass_exchange_loss), 0), 2) land_mass_exchange_loss,
    round(greatest(avg(population_exchange_loss), 0), 2) population_exchange_loss,
    round(avg(refugees_originated), 2) refugees_originated,
    round(avg(refugees_hosted), 2) refugees_hosted,
    round(avg(internally_displaced_persons), 2) internally_displaced_persons,
    round(avg(concurrent_wars), 2) concurrent_wars
from participant_year_descriptives
where start_year = year
group by 1, 2, 3, 4
union all
select
    'y' timeframe,
    war_id,
    war_name,
    c_code,
    round(avg(terrorism_deaths), 2) terrorism_deaths,
    round(avg(mid_dyads), 2) mid_dyads,
    round(avg(mid_dyads_initiated), 2) mid_dyads_initiated,
    round(avg(mid_dyads_targeted), 2) mid_dyads_targeted,
    round(avg(mid_dyads_joined), 2) mid_dyads_joined,
    round(avg(allied_countries), 2) allied_countries,
    round(avg(trade_countries), 2) trade_countries,
    round(avg(money_flow_in), 2) money_flow_in,
    round(avg(money_flow_out), 2) money_flow_out,
    round(avg(imports), 2) imports,
    round(avg(exports), 2) exports,
    round(avg(military_expenditure), 2) military_expenditure,
    round(avg(military_personnel), 2) military_personnel,
    round(avg(iron_steel_production), 2) iron_steel_production,
    round(avg(energy_consumption), 2) energy_consumption,
    round(avg(population), 2) population,
    round(avg(urban_population), 2) urban_population,
    avg(urban_population_growth_rate) urban_population_growth_rate,
    avg(cinc_score) cinc_score,
    round(greatest(avg(land_mass_exchange_gain), 0), 2) land_mass_exchange_gain,
    round(greatest(avg(population_exchange_gain), 0), 2) population_exchange_gain,
    round(greatest(avg(land_mass_exchange_loss), 0), 2) land_mass_exchange_loss,
    round(greatest(avg(population_exchange_loss), 0), 2) population_exchange_loss,
    round(avg(refugees_originated), 2) refugees_originated,
    round(avg(refugees_hosted), 2) refugees_hosted,
    round(avg(internally_displaced_persons), 2) internally_displaced_persons,
    round(avg(concurrent_wars), 2) concurrent_wars
from participant_year_descriptives
where end_year = year
group by 1, 2, 3, 4
union all
select
    'z' timeframe,
    war_id,
    war_name,
    c_code,
    round(avg(terrorism_deaths), 2) terrorism_deaths,
    round(avg(mid_dyads), 2) mid_dyads,
    round(avg(mid_dyads_initiated), 2) mid_dyads_initiated,
    round(avg(mid_dyads_targeted), 2) mid_dyads_targeted,
    round(avg(mid_dyads_joined), 2) mid_dyads_joined,
    round(avg(allied_countries), 2) allied_countries,
    round(avg(trade_countries), 2) trade_countries,
    round(avg(money_flow_in), 2) money_flow_in,
    round(avg(money_flow_out), 2) money_flow_out,
    round(avg(imports), 2) imports,
    round(avg(exports), 2) exports,
    round(avg(military_expenditure), 2) military_expenditure,
    round(avg(military_personnel), 2) military_personnel,
    round(avg(iron_steel_production), 2) iron_steel_production,
    round(avg(energy_consumption), 2) energy_consumption,
    round(avg(population), 2) population,
    round(avg(urban_population), 2) urban_population,
    avg(urban_population_growth_rate) urban_population_growth_rate,
    avg(cinc_score) cinc_score,
    round(greatest(avg(land_mass_exchange_gain), 0), 2) land_mass_exchange_gain,
    round(greatest(avg(population_exchange_gain), 0), 2) population_exchange_gain,
    round(greatest(avg(land_mass_exchange_loss), 0), 2) land_mass_exchange_loss,
    round(greatest(avg(population_exchange_loss), 0), 2) population_exchange_loss,
    round(avg(refugees_originated), 2) refugees_originated,
    round(avg(refugees_hosted), 2) refugees_hosted,
    round(avg(internally_displaced_persons), 2) internally_displaced_persons,
    round(avg(concurrent_wars), 2) concurrent_wars
from participant_year_descriptives
group by 1, 2, 3, 4)

select
    a.war_id,
    a.war_name,
    a.c_code,
    a.participant,
    a.side,
    a.start_date,
    a.end_date,
    a.start_year,
    a.end_year,
    a.start_date_estimated,
    a.end_date_estimated,
    a.battle_deaths,
    a.battle_deaths_estimated,
    b.terrorism_deaths terrorism_deaths_x,
    b.mid_dyads mid_dyads_x,
    b.mid_dyads_initiated mid_dyads_initiated_x,
    b.mid_dyads_targeted mid_dyads_targeted_x,
    b.mid_dyads_joined mid_dyads_joined_x,
    b.allied_countries allied_countries_x,
    b.trade_countries trade_countries_x,
    b.money_flow_in money_flow_in_x,
    b.money_flow_out money_flow_out_x,
    b.imports imports_x,
    b.exports exports_x,
    b.military_expenditure military_expenditure_x,
    b.military_personnel military_personnel_x,
    b.iron_steel_production iron_steel_production_x,
    b.energy_consumption energy_consumption_x,
    b.population population_x,
    b.urban_population urban_population_x,
    b.urban_population_growth_rate urban_population_growth_rate_x,
    b.cinc_score cinc_score_x,
    b.land_mass_exchange_gain land_mass_exchange_gain_x,
    b.population_exchange_gain population_exchange_gain_x,
    b.land_mass_exchange_loss land_mass_exchange_loss_x,
    b.population_exchange_loss population_exchange_loss_x,
    b.refugees_originated refugees_originated_x,
    b.refugees_hosted refugees_hosted_x,
    b.internally_displaced_persons internally_displaced_persons_x,
    b.concurrent_wars concurrent_wars_x,
    c.terrorism_deaths terrorism_deaths_y,
    c.mid_dyads mid_dyads_y,
    c.mid_dyads_initiated mid_dyads_initiated_y,
    c.mid_dyads_targeted mid_dyads_targeted_y,
    c.mid_dyads_joined mid_dyads_joined_y,
    c.allied_countries allied_countries_y,
    c.trade_countries trade_countries_y,
    c.money_flow_in money_flow_in_y,
    c.money_flow_out money_flow_out_y,
    c.imports imports_y,
    c.exports exports_y,
    c.military_expenditure military_expenditure_y,
    c.military_personnel military_personnel_y,
    c.iron_steel_production iron_steel_production_y,
    c.energy_consumption energy_consumption_y,
    c.population population_y,
    c.urban_population urban_population_y,
    c.urban_population_growth_rate urban_population_growth_rate_y,
    c.cinc_score cinc_score_y,
    c.land_mass_exchange_gain land_mass_exchange_gain_y,
    c.population_exchange_gain population_exchange_gain_y,
    c.land_mass_exchange_loss land_mass_exchange_loss_y,
    c.population_exchange_loss population_exchange_loss_y,
    c.refugees_originated refugees_originated_y,
    c.refugees_hosted refugees_hosted_y,
    c.internally_displaced_persons internally_displaced_persons_y,
    c.concurrent_wars concurrent_wars_y,
    d.terrorism_deaths terrorism_deaths_z,
    d.mid_dyads mid_dyads_z,
    d.mid_dyads_initiated mid_dyads_initiated_z,
    d.mid_dyads_targeted mid_dyads_targeted_z,
    d.mid_dyads_joined mid_dyads_joined_z,
    d.allied_countries allied_countries_z,
    d.trade_countries trade_countries_z,
    d.money_flow_in money_flow_in_z,
    d.money_flow_out money_flow_out_z,
    d.imports imports_z,
    d.exports exports_z,
    d.military_expenditure military_expenditure_z,
    d.military_personnel military_personnel_z,
    d.iron_steel_production iron_steel_production_z,
    d.energy_consumption energy_consumption_z,
    d.population population_z,
    d.urban_population urban_population_z,
    d.urban_population_growth_rate urban_population_growth_rate_z,
    d.cinc_score cinc_score_z,
    d.land_mass_exchange_gain land_mass_exchange_gain_z,
    d.population_exchange_gain population_exchange_gain_z,
    d.land_mass_exchange_loss land_mass_exchange_loss_z,
    d.population_exchange_loss population_exchange_loss_z,
    d.refugees_originated refugees_originated_z,
    d.refugees_hosted refugees_hosted_z,
    d.internally_displaced_persons internally_displaced_persons_z,
    d.concurrent_wars concurrent_wars_z
from base_participants a
left join participant_descriptor_summaries b on a.war_id = b.war_id
                                             and a.war_name = b.war_name
                                             and a.c_code = b.c_code
                                             and b.timeframe = 'x'
left join participant_descriptor_summaries c on a.war_id = c.war_id
                                             and a.war_name = c.war_name
                                             and a.c_code = c.c_code
                                             and c.timeframe = 'y'
left join participant_descriptor_summaries d on a.war_id = d.war_id
                                             and a.war_name = d.war_name
                                             and a.c_code = d.c_code
                                             and d.timeframe = 'z';
