create or replace table dyadic_descriptives as

select
    a.war_id,
    a.war_name,
    a.c_code_a,
    a.c_code_b,
    a.participant_a,
    a.participant_b,
    'First Year' timeframe,
    max(territory_exchange) territory_exchange,
    max(colonial_contiguity) colonial_contiguity,
    max(contiguity) contiguity,
    max(alliance) alliance,
    max(defense_cooperation_agreements) defense_cooperation_agreements,
    max(inter_governmental_organizations) inter_governmental_organizations,
    max(diplomatic_exchange) diplomatic_exchange,
    max(trade_relations) trade_relations,
    max(same_leader_type) same_leader_type,
    max(military_leaders) military_leaders,
    max(communist_leaders) communist_leaders,
    max(royal_leaders) royal_leaders,
    max(democratic_incumbent) democratic_incumbent,
    max(unconstitutional_incumbent) unconstitutional_incumbent,
    max(democratic_regimes) democratic_regimes,
    max(dictatorships) dictatorships,
    max(collective_leaderships) collective_leaderships,
    max(direct_election) direct_election,
    max(indirect_election) indirect_election,
    max(non_elected_leaders) non_elected_leaders,
    max(no_legislature) no_legislature,
    max(non_elective_legislature) non_elective_legislature,
    max(elective_legislature) elective_legislature,
    max(no_partisan_legislature_legal) no_partisan_legislature_legal,
    max(no_non_regime_legislature_parties_legal) no_non_regime_legislature_parties_legal,
    max(multi_party_legislature_legal) multi_party_legislature_legal,
    max(all_parties_illegal) all_parties_illegal,
    max(single_party_state_exists) single_party_state_exists,
    max(multi_party_state_exists) multi_party_state_exists,
    max(no_parties_exist) no_parties_exist,
    max(one_party_exists) one_party_exists,
    max(no_non_regime_parties_exist) no_non_regime_parties_exist,
    max(leader_died) leader_died,
    max(new_leader) new_leader,
    max(transition_to_democracy) transition_to_democracy,
    max(transition_to_dictatorship) transition_to_dictatorship,
    max(atop) atop,
    max(mtops) mtops,
    max(shared_arms_technology) shared_arms_technology
from dyad_year_descriptives a
join wars b on a.war_id = b.war_id
where
    a.start_year = a.year
    and extract(year from b.start_date)::integer != extract(year from b.end_date)::integer
group by 1, 2, 3, 4, 5, 6, 7
union all
select
    a.war_id,
    a.war_name,
    a.c_code_a,
    a.c_code_b,
    a.participant_a,
    a.participant_b,
    'Last Year' timeframe,
    max(territory_exchange) territory_exchange,
    max(colonial_contiguity) colonial_contiguity,
    max(contiguity) contiguity,
    max(alliance) alliance,
    max(defense_cooperation_agreements) defense_cooperation_agreements,
    max(inter_governmental_organizations) inter_governmental_organizations,
    max(diplomatic_exchange) diplomatic_exchange,
    max(trade_relations) trade_relations,
    max(same_leader_type) same_leader_type,
    max(military_leaders) military_leaders,
    max(communist_leaders) communist_leaders,
    max(royal_leaders) royal_leaders,
    max(democratic_incumbent) democratic_incumbent,
    max(unconstitutional_incumbent) unconstitutional_incumbent,
    max(democratic_regimes) democratic_regimes,
    max(dictatorships) dictatorships,
    max(collective_leaderships) collective_leaderships,
    max(direct_election) direct_election,
    max(indirect_election) indirect_election,
    max(non_elected_leaders) non_elected_leaders,
    max(no_legislature) no_legislature,
    max(non_elective_legislature) non_elective_legislature,
    max(elective_legislature) elective_legislature,
    max(no_partisan_legislature_legal) no_partisan_legislature_legal,
    max(no_non_regime_legislature_parties_legal) no_non_regime_legislature_parties_legal,
    max(multi_party_legislature_legal) multi_party_legislature_legal,
    max(all_parties_illegal) all_parties_illegal,
    max(single_party_state_exists) single_party_state_exists,
    max(multi_party_state_exists) multi_party_state_exists,
    max(no_parties_exist) no_parties_exist,
    max(one_party_exists) one_party_exists,
    max(no_non_regime_parties_exist) no_non_regime_parties_exist,
    max(leader_died) leader_died,
    max(new_leader) new_leader,
    max(transition_to_democracy) transition_to_democracy,
    max(transition_to_dictatorship) transition_to_dictatorship,
    max(atop) atop,
    max(mtops) mtops,
    max(shared_arms_technology) shared_arms_technology
from dyad_year_descriptives a
join wars b on a.war_id = b.war_id
where
    a.end_year = a.year
    and extract(year from b.start_date)::integer != extract(year from b.end_date)::integer
group by 1, 2, 3, 4, 5, 6, 7
union all
select
    war_id,
    war_name,
    c_code_a,
    c_code_b,
    participant_a,
    participant_b,
    'All Years' timeframe,
    max(territory_exchange) territory_exchange,
    max(colonial_contiguity) colonial_contiguity,
    max(contiguity) contiguity,
    max(alliance) alliance,
    max(defense_cooperation_agreements) defense_cooperation_agreements,
    max(inter_governmental_organizations) inter_governmental_organizations,
    max(diplomatic_exchange) diplomatic_exchange,
    max(trade_relations) trade_relations,
    max(same_leader_type) same_leader_type,
    max(military_leaders) military_leaders,
    max(communist_leaders) communist_leaders,
    max(royal_leaders) royal_leaders,
    max(democratic_incumbent) democratic_incumbent,
    max(unconstitutional_incumbent) unconstitutional_incumbent,
    max(democratic_regimes) democratic_regimes,
    max(dictatorships) dictatorships,
    max(collective_leaderships) collective_leaderships,
    max(direct_election) direct_election,
    max(indirect_election) indirect_election,
    max(non_elected_leaders) non_elected_leaders,
    max(no_legislature) no_legislature,
    max(non_elective_legislature) non_elective_legislature,
    max(elective_legislature) elective_legislature,
    max(no_partisan_legislature_legal) no_partisan_legislature_legal,
    max(no_non_regime_legislature_parties_legal) no_non_regime_legislature_parties_legal,
    max(multi_party_legislature_legal) multi_party_legislature_legal,
    max(all_parties_illegal) all_parties_illegal,
    max(single_party_state_exists) single_party_state_exists,
    max(multi_party_state_exists) multi_party_state_exists,
    max(no_parties_exist) no_parties_exist,
    max(one_party_exists) one_party_exists,
    max(no_non_regime_parties_exist) no_non_regime_parties_exist,
    max(leader_died) leader_died,
    max(new_leader) new_leader,
    max(transition_to_democracy) transition_to_democracy,
    max(transition_to_dictatorship) transition_to_dictatorship,
    max(atop) atop,
    max(mtops) mtops,
    max(shared_arms_technology) shared_arms_technology
from dyad_year_descriptives
group by 1, 2, 3, 4, 5, 6, 7;
