create or replace table dyadic_descriptives as

with

base_dyads as (

select
    a.war_id,
    b.war_name,
    a.c_code_a,
    a.c_code_b,
    a.participant_a,
    a.participant_b,
    a.start_date,
    a.end_date,
    extract(year from a.start_date)::integer start_year,
    extract(year from a.end_date)::integer end_year,
    a.start_date_estimated,
    a.end_date_estimated
from dyads a
join wars b on a.war_id = b.war_id),

dyad_descriptor_summaries as (

select
    'x' timeframe,
    war_id,
    war_name,
    c_code_a,
    c_code_b,
    participant_a,
    participant_b,
    max(territory_exchange) territory_exchange,
    max(colonial_contiguity) colonial_contiguity,
    max(contiguity) contiguity,
    max(alliance) alliance,
    max(defense_cooperation_agreements) defense_cooperation_agreements,
    max(inter_governmental_organizations) inter_governmental_organizations,
    max(diplomatic_exchange) diplomatic_exchange,
    max(trade_relations) trade_relations,
    max(same_leader_type) same_leader_type,
    max(military_leaders) military_leaders,
    max(communist_leaders) communist_leaders,
    max(royal_leaders) royal_leaders,
    max(democratic_incumbent) democratic_incumbent,
    max(unconstitutional_incumbent) unconstitutional_incumbent,
    max(democratic_regimes) democratic_regimes,
    max(dictatorships) dictatorships,
    max(collective_leaderships) collective_leaderships,
    max(direct_election) direct_election,
    max(indirect_election) indirect_election,
    max(non_elected_leaders) non_elected_leaders,
    max(no_legislature) no_legislature,
    max(non_elective_legislature) non_elective_legislature,
    max(elective_legislature) elective_legislature,
    max(no_partisan_legislature_legal) no_partisan_legislature_legal,
    max(no_non_regime_legislature_parties_legal) no_non_regime_legislature_parties_legal,
    max(multi_party_legislature_legal) multi_party_legislature_legal,
    max(all_parties_illegal) all_parties_illegal,
    max(single_party_state_exists) single_party_state_exists,
    max(multi_party_state_exists) multi_party_state_exists,
    max(no_parties_exist) no_parties_exist,
    max(one_party_exists) one_party_exists,
    max(no_non_regime_parties_exist) no_non_regime_parties_exist,
    max(leader_died) leader_died,
    max(new_leader) new_leader,
    max(transition_to_democracy) transition_to_democracy,
    max(transition_to_dictatorship) transition_to_dictatorship,
    max(atop) atop,
    max(mtops) mtops
from dyad_year_descriptives
where start_year = year
group by 1, 2, 3, 4, 5, 6, 7
union all
select
    'y' timeframe,
    war_id,
    war_name,
    c_code_a,
    c_code_b,
    participant_a,
    participant_b,
    max(territory_exchange) territory_exchange,
    max(colonial_contiguity) colonial_contiguity,
    max(contiguity) contiguity,
    max(alliance) alliance,
    max(defense_cooperation_agreements) defense_cooperation_agreements,
    max(inter_governmental_organizations) inter_governmental_organizations,
    max(diplomatic_exchange) diplomatic_exchange,
    max(trade_relations) trade_relations,
    max(same_leader_type) same_leader_type,
    max(military_leaders) military_leaders,
    max(communist_leaders) communist_leaders,
    max(royal_leaders) royal_leaders,
    max(democratic_incumbent) democratic_incumbent,
    max(unconstitutional_incumbent) unconstitutional_incumbent,
    max(democratic_regimes) democratic_regimes,
    max(dictatorships) dictatorships,
    max(collective_leaderships) collective_leaderships,
    max(direct_election) direct_election,
    max(indirect_election) indirect_election,
    max(non_elected_leaders) non_elected_leaders,
    max(no_legislature) no_legislature,
    max(non_elective_legislature) non_elective_legislature,
    max(elective_legislature) elective_legislature,
    max(no_partisan_legislature_legal) no_partisan_legislature_legal,
    max(no_non_regime_legislature_parties_legal) no_non_regime_legislature_parties_legal,
    max(multi_party_legislature_legal) multi_party_legislature_legal,
    max(all_parties_illegal) all_parties_illegal,
    max(single_party_state_exists) single_party_state_exists,
    max(multi_party_state_exists) multi_party_state_exists,
    max(no_parties_exist) no_parties_exist,
    max(one_party_exists) one_party_exists,
    max(no_non_regime_parties_exist) no_non_regime_parties_exist,
    max(leader_died) leader_died,
    max(new_leader) new_leader,
    max(transition_to_democracy) transition_to_democracy,
    max(transition_to_dictatorship) transition_to_dictatorship,
    max(atop) atop,
    max(mtops) mtops
from dyad_year_descriptives
where end_year = year
group by 1, 2, 3, 4, 5, 6, 7
union all
select
    'z' timeframe,
    war_id,
    war_name,
    c_code_a,
    c_code_b,
    participant_a,
    participant_b,
    max(territory_exchange) territory_exchange,
    max(colonial_contiguity) colonial_contiguity,
    max(contiguity) contiguity,
    max(alliance) alliance,
    max(defense_cooperation_agreements) defense_cooperation_agreements,
    max(inter_governmental_organizations) inter_governmental_organizations,
    max(diplomatic_exchange) diplomatic_exchange,
    max(trade_relations) trade_relations,
    max(same_leader_type) same_leader_type,
    max(military_leaders) military_leaders,
    max(communist_leaders) communist_leaders,
    max(royal_leaders) royal_leaders,
    max(democratic_incumbent) democratic_incumbent,
    max(unconstitutional_incumbent) unconstitutional_incumbent,
    max(democratic_regimes) democratic_regimes,
    max(dictatorships) dictatorships,
    max(collective_leaderships) collective_leaderships,
    max(direct_election) direct_election,
    max(indirect_election) indirect_election,
    max(non_elected_leaders) non_elected_leaders,
    max(no_legislature) no_legislature,
    max(non_elective_legislature) non_elective_legislature,
    max(elective_legislature) elective_legislature,
    max(no_partisan_legislature_legal) no_partisan_legislature_legal,
    max(no_non_regime_legislature_parties_legal) no_non_regime_legislature_parties_legal,
    max(multi_party_legislature_legal) multi_party_legislature_legal,
    max(all_parties_illegal) all_parties_illegal,
    max(single_party_state_exists) single_party_state_exists,
    max(multi_party_state_exists) multi_party_state_exists,
    max(no_parties_exist) no_parties_exist,
    max(one_party_exists) one_party_exists,
    max(no_non_regime_parties_exist) no_non_regime_parties_exist,
    max(leader_died) leader_died,
    max(new_leader) new_leader,
    max(transition_to_democracy) transition_to_democracy,
    max(transition_to_dictatorship) transition_to_dictatorship,
    max(atop) atop,
    max(mtops) mtops
from dyad_year_descriptives
group by 1, 2, 3, 4, 5, 6, 7)

select
    a.war_id,
    a.war_name,
    a.c_code_a,
    a.c_code_b,
    a.participant_a,
    a.participant_b,
    a.start_date,
    a.end_date,
    a.start_year,
    a.end_year,
    a.start_date_estimated,
    a.end_date_estimated,
    b.territory_exchange territory_exchange_x,
    b.colonial_contiguity colonial_contiguity_x,
    b.contiguity contiguity_x,
    b.alliance alliance_x,
    b.defense_cooperation_agreements defense_cooperation_agreements_x,
    b.inter_governmental_organizations inter_governmental_organizations_x,
    b.diplomatic_exchange diplomatic_exchange_x,
    b.trade_relations trade_relations_x,
    b.same_leader_type same_leader_type_x,
    b.military_leaders military_leaders_x,
    b.communist_leaders communist_leaders_x,
    b.royal_leaders royal_leaders_x,
    b.democratic_incumbent democratic_incumbent_x,
    b.unconstitutional_incumbent unconstitutional_incumbent_x,
    b.democratic_regimes democratic_regimes_x,
    b.dictatorships dictatorships_x,
    b.collective_leaderships collective_leaderships_x,
    b.direct_election direct_election_x,
    b.indirect_election indirect_election_x,
    b.non_elected_leaders non_elected_leaders_x,
    b.no_legislature no_legislature_x,
    b.non_elective_legislature non_elective_legislature_x,
    b.elective_legislature elective_legislature_x,
    b.no_partisan_legislature_legal no_partisan_legislature_legal_x,
    b.no_non_regime_legislature_parties_legal no_non_regime_legislature_parties_legal_x,
    b.multi_party_legislature_legal multi_party_legislature_legal_x,
    b.all_parties_illegal all_parties_illegal_x,
    b.single_party_state_exists single_party_state_exists_x,
    b.multi_party_state_exists multi_party_state_exists_x,
    b.no_parties_exist no_parties_exist_x,
    b.one_party_exists one_party_exists_x,
    b.no_non_regime_parties_exist no_non_regime_parties_exist_x,
    b.leader_died leader_died_x,
    b.new_leader new_leader_x,
    b.transition_to_democracy transition_to_democracy_x,
    b.transition_to_dictatorship transition_to_dictatorship_x,
    b.atop atop_x,
    b.mtops mtops_x,
    c.territory_exchange territory_exchange_y,
    c.colonial_contiguity colonial_contiguity_y,
    c.contiguity contiguity_y,
    c.alliance alliance_y,
    c.defense_cooperation_agreements defense_cooperation_agreements_y,
    c.inter_governmental_organizations inter_governmental_organizations_y,
    c.diplomatic_exchange diplomatic_exchange_y,
    c.trade_relations trade_relations_y,
    c.same_leader_type same_leader_type_y,
    c.military_leaders military_leaders_y,
    c.communist_leaders communist_leaders_y,
    c.royal_leaders royal_leaders_y,
    c.democratic_incumbent democratic_incumbent_y,
    c.unconstitutional_incumbent unconstitutional_incumbent_y,
    c.democratic_regimes democratic_regimes_y,
    c.dictatorships dictatorships_y,
    c.collective_leaderships collective_leaderships_y,
    c.direct_election direct_election_y,
    c.indirect_election indirect_election_y,
    c.non_elected_leaders non_elected_leaders_y,
    c.no_legislature no_legislature_y,
    c.non_elective_legislature non_elective_legislature_y,
    c.elective_legislature elective_legislature_y,
    c.no_partisan_legislature_legal no_partisan_legislature_legal_y,
    c.no_non_regime_legislature_parties_legal no_non_regime_legislature_parties_legal_y,
    c.multi_party_legislature_legal multi_party_legislature_legal_y,
    c.all_parties_illegal all_parties_illegal_y,
    c.single_party_state_exists single_party_state_exists_y,
    c.multi_party_state_exists multi_party_state_exists_y,
    c.no_parties_exist no_parties_exist_y,
    c.one_party_exists one_party_exists_y,
    c.no_non_regime_parties_exist no_non_regime_parties_exist_y,
    c.leader_died leader_died_y,
    c.new_leader new_leader_y,
    c.transition_to_democracy transition_to_democracy_y,
    c.transition_to_dictatorship transition_to_dictatorship_y,
    c.atop atop_y,
    c.mtops mtops_y,
    d.territory_exchange territory_exchange_z,
    d.colonial_contiguity colonial_contiguity_z,
    d.contiguity contiguity_z,
    d.alliance alliance_z,
    d.defense_cooperation_agreements defense_cooperation_agreements_z,
    d.inter_governmental_organizations inter_governmental_organizations_z,
    d.diplomatic_exchange diplomatic_exchange_z,
    d.trade_relations trade_relations_z,
    d.same_leader_type same_leader_type_z,
    d.military_leaders military_leaders_z,
    d.communist_leaders communist_leaders_z,
    d.royal_leaders royal_leaders_z,
    d.democratic_incumbent democratic_incumbent_z,
    d.unconstitutional_incumbent unconstitutional_incumbent_z,
    d.democratic_regimes democratic_regimes_z,
    d.dictatorships dictatorships_z,
    d.collective_leaderships collective_leaderships_z,
    d.direct_election direct_election_z,
    d.indirect_election indirect_election_z,
    d.non_elected_leaders non_elected_leaders_z,
    d.no_legislature no_legislature_z,
    d.non_elective_legislature non_elective_legislature_z,
    d.elective_legislature elective_legislature_z,
    d.no_partisan_legislature_legal no_partisan_legislature_legal_z,
    d.no_non_regime_legislature_parties_legal no_non_regime_legislature_parties_legal_z,
    d.multi_party_legislature_legal multi_party_legislature_legal_z,
    d.all_parties_illegal all_parties_illegal_z,
    d.single_party_state_exists single_party_state_exists_z,
    d.multi_party_state_exists multi_party_state_exists_z,
    d.no_parties_exist no_parties_exist_z,
    d.one_party_exists one_party_exists_z,
    d.no_non_regime_parties_exist no_non_regime_parties_exist_z,
    d.leader_died leader_died_z,
    d.new_leader new_leader_z,
    d.transition_to_democracy transition_to_democracy_z,
    d.transition_to_dictatorship transition_to_dictatorship_z,
    d.atop atop_z,
    d.mtops mtops_z
from base_dyads a
left join dyad_descriptor_summaries b on a.war_id = b.war_id
                                      and a.war_name = b.war_name
                                      and a.c_code_a = b.c_code_a
                                      and a.c_code_b = b.c_code_b
                                      and a.participant_a = b.participant_a
                                      and a.participant_b = b.participant_b
                                      and b.timeframe = 'x'
left join dyad_descriptor_summaries c on a.war_id = c.war_id
                                      and a.war_name = c.war_name
                                      and a.c_code_a = c.c_code_a
                                      and a.c_code_b = c.c_code_b
                                      and a.participant_a = c.participant_a
                                      and a.participant_b = c.participant_b
                                      and c.timeframe = 'y'
left join dyad_descriptor_summaries d on a.war_id = d.war_id
                                      and a.war_name = d.war_name
                                      and a.c_code_a = d.c_code_a
                                      and a.c_code_b = d.c_code_b
                                      and a.participant_a = d.participant_a
                                      and a.participant_b = d.participant_b
                                      and d.timeframe = 'z';
